#!/usr/bin/env python3
"""Patch the generated Android MainActivity with a safe-area inset bridge.

Why this exists
---------------
The frontend positions every bottom bar with
`var(--inset-bottom, env(safe-area-inset-bottom, 0px))` (see
`src/ui/design/tokens.ts`). iOS resolves the `env()` fallback natively, but
Android's Chromium WebView reports 0 for the system bars — the host activity
has to measure `WindowInsets` itself and hand them to the page. The Tauri
template's MainActivity calls `enableEdgeToEdge()` (and Android 15+ enforces
edge-to-edge anyway with targetSdk >= 35), so without this patch the WebView
extends under the navigation bar and the bottom ~48dp of every screen is
covered by the system bars.

`tauri android init` regenerates `src-tauri/gen/android` from scratch, so the
fix cannot live in the scaffold: CI (`.github/workflows/build-mobile.yml`) and
local builds must both run this script AFTER `tauri android init` and BEFORE
the gradle build.

How the bridge avoids the startup race
--------------------------------------
A naive `evaluateJavascript("...setProperty('--inset-bottom',...)")` from the
insets listener fires during activity startup, before the real document has
loaded — the CSS variables land on the initial blank document and are gone by
the time the app renders, which resurfaces the bug on every cold start.
`addJavascriptInterface` alone is not enough either: Android only exposes the
interface object to documents loaded AFTER registration, and wry starts
loading the app URL before `onWebViewCreate` hands us the WebView, so on a
cold start the first document may never see `window.ReachyNativeInsets`.

The reliable channel is therefore an ACKed push: the activity re-evaluates
`window.__reachyApplyInsets(...)` every 400ms until the page's own handler
(defined by `src/shared/android-insets.ts`) answers 'ok' through the
`evaluateJavascript` result callback. Whatever the load ordering, the push
lands as soon as the bundle has booted, and each later inset change (bar mode
toggles, foldables) restarts the loop. The `addJavascriptInterface` pull is
kept as belt-and-braces for reloaded documents.

Idempotent: re-running on an already patched scaffold is a no-op (the
version marker below changes whenever the template does, so an outdated
patched scaffold is re-patched).
"""

from __future__ import annotations

import pathlib
import re
import sys

MARKER = "reachy-insets-bridge-v2"

TEMPLATE = """package {package}

// reachy-insets-bridge-v2 (generated by scripts/patch-android-insets.py)

import android.annotation.SuppressLint
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.view.View
import android.webkit.JavascriptInterface
import android.webkit.WebView
import androidx.activity.enableEdgeToEdge
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat

class MainActivity : TauriActivity() {{
  // Latest system-bars + display-cutout insets in CSS pixels, as JSON. Read
  // from the WebView's JS thread through the bridge below, written from the
  // UI thread by the insets listener - hence @Volatile.
  @Volatile private var insetsJson = "{{\\"top\\":0,\\"bottom\\":0,\\"left\\":0,\\"right\\":0}}"
  private var webView: WebView? = null
  private val handler = Handler(Looper.getMainLooper())
  // Push-until-ACK state: `delivered` flips once the page's handler answers
  // 'ok'; each inset change resets it so updates propagate too. The retry
  // budget only guards against a document that never defines the handler
  // (60s at 400ms).
  private var delivered = false
  private var retriesLeft = 0

  private val pusher = object : Runnable {{
    override fun run() {{
      if (delivered || retriesLeft-- <= 0) return
      webView?.evaluateJavascript(
        "typeof window.__reachyApplyInsets==='function'" +
          "?(window.__reachyApplyInsets($insetsJson),'ok'):'no'"
      ) {{ result -> if (result != null && result.contains("ok")) delivered = true }}
      handler.postDelayed(this, 400)
    }}
  }}

  private fun startPushing() {{
    delivered = false
    retriesLeft = 150
    handler.removeCallbacks(pusher)
    handler.post(pusher)
  }}

  override fun onCreate(savedInstanceState: Bundle?) {{
    enableEdgeToEdge()
    super.onCreate(savedInstanceState)
    val content = findViewById<View>(android.R.id.content)
    ViewCompat.setOnApplyWindowInsetsListener(content) {{ _, insets ->
      val sys = insets.getInsets(
        WindowInsetsCompat.Type.systemBars() or WindowInsetsCompat.Type.displayCutout()
      )
      val d = resources.displayMetrics.density
      insetsJson = "{{\\"top\\":${{(sys.top / d).toInt()}},\\"bottom\\":${{(sys.bottom / d).toInt()}}," +
        "\\"left\\":${{(sys.left / d).toInt()}},\\"right\\":${{(sys.right / d).toInt()}}}}"
      startPushing()
      insets
    }}
    ViewCompat.requestApplyInsets(content)
  }}

  @SuppressLint("AddJavascriptInterface")
  override fun onWebViewCreate(webView: WebView) {{
    this.webView = webView
    // Only visible to documents loaded from now on (Android contract), so
    // the first document usually can't see it - the ACKed push above is the
    // reliable channel. Kept for reloaded documents, where the pull answers
    // instantly without waiting for a push cycle.
    webView.addJavascriptInterface(InsetsBridge(), "ReachyNativeInsets")
    startPushing()
  }}

  inner class InsetsBridge {{
    @JavascriptInterface
    fun get(): String = insetsJson
  }}
}}
"""


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    candidates = sorted(
        (root / "src-tauri/gen/android/app/src/main/java").rglob("MainActivity.kt")
    )
    if not candidates:
        print(
            "patch-android-insets: MainActivity.kt not found - run `tauri android init` first.",
            file=sys.stderr,
        )
        return 1
    path = candidates[0]
    source = path.read_text()
    if MARKER in source:
        print(f"patch-android-insets: {path} already patched.")
        return 0
    match = re.match(r"\s*package\s+([\w.]+)", source)
    if not match:
        print(f"patch-android-insets: no package declaration in {path}.", file=sys.stderr)
        return 1
    path.write_text(TEMPLATE.format(package=match.group(1)))
    print(f"patch-android-insets: patched {path}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
